all: asm iss mult mult_table mult_dma pipe_dma

asm: asm.c
	gcc -Wall asm.c -o asm
iss: iss.c
	gcc -Wall iss.c -o iss
mult: mult.c
	gcc -Wall mult.c -o mult
mult_dma: mult_dma.c
	gcc -Wall mult_dma.c -o mult_dma
pipe_dma: pipe_dma.c
	gcc -Wall pipe_dma.c -o pipe_dma
mult_table: mult_table.c
	gcc -Wall mult_table.c -o mult_table
